spring:
  application:
    name: mypay-core
  profiles:
      active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /mpay
---
#开发环境配置
server:
  port: 9966

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: knight1016
    username: knight
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 30
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        login-username: druid
        login-password: druid